-- ═══════════════════════════════════════════════════════════════════
-- PR48 (restructure PR E) — emit_taller_certificado(p_inscripcion_id,
--                                                    p_codigo_verificacion).
--
-- Fase 5 GdV-parity restructure. Additive + forward-only. Adds ONE new
-- SECURITY DEFINER RPC that mints the completion certificate for an
-- inscription and computes every *_snapshot column from the DB.
--
-- WHY AN RPC (not a plain INSERT under RLS): Postgres checks the table
-- GRANT layer BEFORE RLS. `authenticated` holds only SELECT on
-- public.taller_certificados (INSERT is service_role only); a cookie-bound
-- authenticated INSERT would fail "permission denied" regardless of the
-- RLS INSERT policy. So the intended write path is a SECURITY DEFINER RPC
-- that inserts with definer privileges, staying safe by gating internally
-- on director.write OR admin.manage — same shape as generate_taller_sesiones
-- (PR47) and open_edicion (PR35).
--
-- RESOLUTION CHAIN (inscripción -> edición -> abstract taller + persona):
--   taller_inscripciones.taller_id            (references the EDICIÓN)
--     -> taller_ediciones.id
--   taller_ediciones.taller_id                (references the ABSTRACT)
--     -> talleres.id            -> talleres.nombre  (nombre_taller_snapshot)
--   taller_inscripciones.persona_principal_id
--     -> usuarios.id            -> nombre + apellido (nombre_participante_snapshot)
-- NOTE: taller_certificados.taller_id references talleres_crecimiento_metadata
-- (renamed taller_ediciones), so it equals taller_inscripciones.taller_id.
--
-- FIRMANTES SNAPSHOT: taller_ediciones.firmantes is jsonb OBJECTS
--   {persona_id, rol_etiqueta, orden}. The PUBLIC verify endpoint
--   (app/api/public/verificar-certificado/[codigo]) projects
--   firmantes_snapshot filtering to STRING elements, so raw objects would
--   render as ZERO signers. This RPC transforms objects -> string[]:
--   "Nombre Apellido (Rol)" ordered by `orden`, resolving names from
--   usuarios so the snapshot is immutable even if a signer is later renamed.
--
-- CODE: p_codigo_verificacion is generated app-side (16-char locked ALPHABET
--   in lib/platform/talleres/certificates.ts) and validated here against the
--   table CHECK(length = 16). The RPC does NOT generate the code — keeping
--   the alphabet in one place (the app) that isValidCertificateCode enforces.
--
-- IDEMPOTENT: UNIQUE(inscripcion_id) + ON CONFLICT (inscripcion_id) DO
--   NOTHING. A second call is a no-op and returns the existing certificate
--   (created=false) — the code is minted exactly once and never rotated.
--
-- GATE: director.write OR admin.manage. Called from the completion
--   transition (app/api/talleres/inscripciones/[id]/transition) after
--   unit_estado is set to 'completado'; the RPC also defends that invariant.
--
-- ⚠️ LIVE PRODUCTION — additive only (no DROP / TRUNCATE). Authored +
-- tested (static SQL) on a scratch DB; applying to production is the
-- operator's deploy step.
-- ═══════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION public.emit_taller_certificado(
  p_inscripcion_id      uuid,
  p_codigo_verificacion text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $func$
DECLARE
  v_user_id            uuid;
  v_cap_ok             boolean;
  v_edicion_id         uuid;
  v_persona_id         uuid;
  v_unit_estado        text;
  v_taller_nombre      text;
  v_participante       text;
  v_firmantes_raw      jsonb;
  v_firmantes_snapshot jsonb;
  v_cert_id            uuid;
BEGIN
  -- 1. Auth + capability gate (director.write OR admin.manage).
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'UNAUTHENTICATED' USING ERRCODE = '42501';
  END IF;

  v_cap_ok := public.auth_has_talleres_capability('talleres_crecimiento.director.write')
              OR public.auth_has_talleres_capability('talleres_crecimiento.admin.manage');
  IF NOT v_cap_ok THEN
    RAISE EXCEPTION 'FORBIDDEN: requires director.write or admin.manage'
      USING ERRCODE = '42501';
  END IF;

  -- 2. Validate the verification code shape (matches the table CHECK and the
  --    app-side ALPHABET). The code is generated by the caller, not here.
  IF p_codigo_verificacion IS NULL OR length(p_codigo_verificacion) <> 16 THEN
    RAISE EXCEPTION 'INVALID_CODIGO: expected a 16-char verification code'
      USING ERRCODE = '22023';
  END IF;

  -- 3. Resolve inscripción -> edición -> abstract taller + principal persona.
  SELECT i.taller_id,
         i.persona_principal_id,
         i.unit_estado,
         t.nombre,
         btrim(concat_ws(' ', u.nombre, u.apellido)),
         e.firmantes
    INTO v_edicion_id,
         v_persona_id,
         v_unit_estado,
         v_taller_nombre,
         v_participante,
         v_firmantes_raw
    FROM public.taller_inscripciones i
    JOIN public.taller_ediciones e ON e.id = i.taller_id
    JOIN public.talleres t ON t.id = e.taller_id
    JOIN public.usuarios u ON u.id = i.persona_principal_id
   WHERE i.id = p_inscripcion_id;

  IF v_edicion_id IS NULL THEN
    RAISE EXCEPTION 'NOT_FOUND: inscripción % has no resolvable edición/persona', p_inscripcion_id
      USING ERRCODE = 'P0002';
  END IF;

  -- 4. Defensive: a certificate is only minted for a completed inscription.
  --    The completion transition sets unit_estado='completado' BEFORE calling
  --    this RPC; guarding it prevents out-of-band certificate minting.
  IF v_unit_estado IS DISTINCT FROM 'completado' THEN
    RAISE EXCEPTION 'INSCRIPCION_NOT_COMPLETED: unit_estado=%', v_unit_estado
      USING ERRCODE = '22023';
  END IF;

  -- 5. Transform edición firmantes (objects {persona_id, rol_etiqueta, orden})
  --    into a string[] snapshot. The public verify endpoint keeps only string
  --    elements, so objects would surface as zero signers. Names resolve from
  --    usuarios and are frozen here (immutable snapshot). Order by `orden`.
  SELECT COALESCE(jsonb_agg(sig ORDER BY ord), '[]'::jsonb)
    INTO v_firmantes_snapshot
    FROM (
      SELECT
        to_jsonb(
          CASE
            WHEN NULLIF(btrim(concat_ws(' ', su.nombre, su.apellido)), '') IS NOT NULL
                 AND COALESCE(f.rol_etiqueta, '') <> ''
              THEN btrim(concat_ws(' ', su.nombre, su.apellido)) || ' (' || f.rol_etiqueta || ')'
            WHEN NULLIF(btrim(concat_ws(' ', su.nombre, su.apellido)), '') IS NOT NULL
              THEN btrim(concat_ws(' ', su.nombre, su.apellido))
            ELSE COALESCE(NULLIF(f.rol_etiqueta, ''), 'Firmante')
          END
        ) AS sig,
        COALESCE(f.orden, 0) AS ord
      FROM jsonb_to_recordset(COALESCE(v_firmantes_raw, '[]'::jsonb))
             AS f(persona_id uuid, rol_etiqueta text, orden integer)
      LEFT JOIN public.usuarios su ON su.id = f.persona_id
    ) s;

  -- 6. Mint the certificate. taller_id stores the EDICIÓN id (that is the FK
  --    target). fecha_completitud defaults to now(); pdf_storage_path stays
  --    NULL (no PDF store wired — the cert verifies by codigo_verificacion).
  INSERT INTO public.taller_certificados (
    inscripcion_id,
    codigo_verificacion,
    taller_id,
    persona_id,
    nombre_taller_snapshot,
    nombre_participante_snapshot,
    firmantes_snapshot
  ) VALUES (
    p_inscripcion_id,
    p_codigo_verificacion,
    v_edicion_id,
    v_persona_id,
    v_taller_nombre,
    v_participante,
    v_firmantes_snapshot
  )
  ON CONFLICT (inscripcion_id) DO NOTHING
  RETURNING id INTO v_cert_id;

  -- 7. Idempotent success: a prior call already minted the certificate (the
  --    code is never rotated), so return the existing one.
  IF v_cert_id IS NULL THEN
    SELECT c.id, c.codigo_verificacion
      INTO v_cert_id, p_codigo_verificacion
      FROM public.taller_certificados c
     WHERE c.inscripcion_id = p_inscripcion_id;

    RETURN jsonb_build_object(
      'ok', true,
      'created', false,
      'certificado_id', v_cert_id,
      'codigo_verificacion', p_codigo_verificacion,
      'inscripcion_id', p_inscripcion_id
    );
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'created', true,
    'certificado_id', v_cert_id,
    'codigo_verificacion', p_codigo_verificacion,
    'inscripcion_id', p_inscripcion_id
  );
END;
$func$;

REVOKE ALL ON FUNCTION public.emit_taller_certificado(uuid, text) FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.emit_taller_certificado(uuid, text) TO authenticated;
