-- Support ticket system foundation.
-- Production safety: additive schema only; no data deletion, truncation, or backfill.

CREATE SCHEMA IF NOT EXISTS support_private;

REVOKE ALL ON SCHEMA support_private FROM PUBLIC;
GRANT USAGE ON SCHEMA support_private TO authenticated, service_role;

CREATE OR REPLACE FUNCTION support_private.current_usuario_id()
RETURNS uuid
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO 'public'
AS $$
  SELECT u.id
  FROM public.usuarios u
  WHERE u.auth_id = (select auth.uid())
  LIMIT 1
$$;

REVOKE ALL ON FUNCTION support_private.current_usuario_id() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION support_private.current_usuario_id() TO authenticated, service_role;

CREATE TABLE IF NOT EXISTS public.support_user_capabilities (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  usuario_id uuid NOT NULL REFERENCES public.usuarios(id),
  capability text NOT NULL CHECK (capability IN ('support.view', 'support.reply', 'support.manage')),
  granted_by_usuario_id uuid REFERENCES public.usuarios(id),
  granted_at timestamptz NOT NULL DEFAULT now(),
  revoked_at timestamptz,
  UNIQUE (usuario_id, capability)
);

CREATE OR REPLACE FUNCTION support_private.has_capability(required_capability text)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO 'public', 'support_private'
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.usuarios u
    JOIN public.usuario_roles ur ON ur.usuario_id = u.id
    JOIN public.roles_sistema rs ON rs.id = ur.rol_id
    JOIN public.support_user_capabilities suc ON suc.usuario_id = u.id
    WHERE u.auth_id = (select auth.uid())
      AND rs.nombre_interno = 'admin'
      AND suc.capability = required_capability
      AND suc.revoked_at IS NULL
  )
$$;

REVOKE ALL ON FUNCTION support_private.has_capability(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION support_private.has_capability(text) TO authenticated, service_role;

CREATE TABLE IF NOT EXISTS public.support_tickets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_number bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  reporter_usuario_id uuid NOT NULL REFERENCES public.usuarios(id),
  assignee_usuario_id uuid REFERENCES public.usuarios(id) ON DELETE SET NULL,
  campus_id uuid REFERENCES public.campus(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'received' CHECK (status IN ('received', 'in_review', 'in_progress', 'resolved', 'closed')),
  category text NOT NULL CHECK (char_length(category) BETWEEN 2 AND 80),
  severity text NOT NULL DEFAULT 'normal' CHECK (severity IN ('low', 'normal', 'high', 'urgent')),
  title text NOT NULL CHECK (char_length(title) BETWEEN 5 AND 160),
  description text NOT NULL CHECK (char_length(description) BETWEEN 10 AND 8000),
  current_route text,
  browser_name text,
  os_name text,
  viewport text,
  app_build_version text,
  sentry_event_id text,
  diagnostics_consent boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  closed_at timestamptz,
  search_vector tsvector GENERATED ALWAYS AS (
    setweight(to_tsvector('simple', coalesce(ticket_number::text, '')), 'A') ||
    setweight(to_tsvector('simple', coalesce(title, '')), 'A') ||
    setweight(to_tsvector('simple', coalesce(description, '')), 'B') ||
    setweight(to_tsvector('simple', coalesce(category, '')), 'C') ||
    setweight(to_tsvector('simple', coalesce(status, '')), 'C')
  ) STORED
);

CREATE TABLE IF NOT EXISTS public.support_ticket_messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id uuid NOT NULL REFERENCES public.support_tickets(id) ON DELETE CASCADE,
  author_usuario_id uuid NOT NULL REFERENCES public.usuarios(id),
  body text NOT NULL CHECK (char_length(body) BETWEEN 1 AND 8000),
  is_internal boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.support_ticket_attachments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id uuid NOT NULL REFERENCES public.support_tickets(id) ON DELETE CASCADE,
  uploaded_by_usuario_id uuid NOT NULL REFERENCES public.usuarios(id),
  kind text NOT NULL CHECK (kind IN ('screenshot', 'video')),
  status text NOT NULL DEFAULT 'pending_upload' CHECK (status IN ('pending_upload', 'uploaded', 'rejected', 'deleted')),
  bucket text NOT NULL DEFAULT 'global-connect-support',
  object_key text NOT NULL UNIQUE,
  original_filename text NOT NULL,
  content_type text NOT NULL,
  byte_size bigint NOT NULL CHECK (byte_size > 0 AND byte_size <= 104857600),
  checksum_sha256 text,
  rejection_reason text,
  retention_expires_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.support_ticket_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id uuid NOT NULL REFERENCES public.support_tickets(id) ON DELETE CASCADE,
  actor_usuario_id uuid REFERENCES public.usuarios(id),
  action text NOT NULL CHECK (char_length(action) BETWEEN 3 AND 120),
  target_type text NOT NULL CHECK (char_length(target_type) BETWEEN 3 AND 80),
  target_id uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  idempotency_key text UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS support_user_capabilities_active_idx ON public.support_user_capabilities(usuario_id, capability) WHERE revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS support_tickets_reporter_idx ON public.support_tickets(reporter_usuario_id, created_at DESC);
CREATE INDEX IF NOT EXISTS support_tickets_status_created_idx ON public.support_tickets(status, created_at DESC);
CREATE INDEX IF NOT EXISTS support_tickets_assignee_idx ON public.support_tickets(assignee_usuario_id) WHERE assignee_usuario_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS support_tickets_campus_idx ON public.support_tickets(campus_id) WHERE campus_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS support_tickets_search_idx ON public.support_tickets USING gin(search_vector);
CREATE INDEX IF NOT EXISTS support_ticket_messages_ticket_created_idx ON public.support_ticket_messages(ticket_id, created_at);
CREATE INDEX IF NOT EXISTS support_ticket_attachments_ticket_idx ON public.support_ticket_attachments(ticket_id);
CREATE INDEX IF NOT EXISTS support_ticket_attachments_pending_idx ON public.support_ticket_attachments(created_at) WHERE status = 'pending_upload';
CREATE INDEX IF NOT EXISTS support_ticket_events_ticket_created_idx ON public.support_ticket_events(ticket_id, created_at);

ALTER TABLE public.support_user_capabilities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_ticket_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_ticket_attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_ticket_events ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON public.support_user_capabilities TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.support_tickets TO authenticated;
GRANT SELECT, INSERT ON public.support_ticket_messages TO authenticated;
GRANT SELECT, INSERT ON public.support_ticket_attachments TO authenticated;
GRANT SELECT ON public.support_ticket_events TO authenticated;

CREATE POLICY support_capabilities_select ON public.support_user_capabilities
  FOR SELECT TO authenticated
  USING (usuario_id = support_private.current_usuario_id() OR support_private.has_capability('support.manage'));

CREATE POLICY support_tickets_select ON public.support_tickets
  FOR SELECT TO authenticated
  USING (reporter_usuario_id = support_private.current_usuario_id() OR support_private.has_capability('support.view'));

CREATE POLICY support_tickets_insert ON public.support_tickets
  FOR INSERT TO authenticated
  WITH CHECK (
    reporter_usuario_id = support_private.current_usuario_id()
    AND assignee_usuario_id IS NULL
    AND status = 'received'
    AND closed_at IS NULL
  );

CREATE POLICY support_tickets_update ON public.support_tickets
  FOR UPDATE TO authenticated
  USING (support_private.has_capability('support.manage'))
  WITH CHECK (support_private.has_capability('support.manage'));

CREATE POLICY support_messages_select ON public.support_ticket_messages
  FOR SELECT TO authenticated
  USING (
    support_private.has_capability('support.view')
    OR (
      is_internal = false
      AND EXISTS (
        SELECT 1 FROM public.support_tickets st
        WHERE st.id = ticket_id
          AND st.reporter_usuario_id = support_private.current_usuario_id()
      )
    )
  );

CREATE POLICY support_messages_insert ON public.support_ticket_messages
  FOR INSERT TO authenticated
  WITH CHECK (
    author_usuario_id = support_private.current_usuario_id()
    AND EXISTS (
      SELECT 1 FROM public.support_tickets st
      WHERE st.id = ticket_id
        AND (
          (st.reporter_usuario_id = support_private.current_usuario_id() AND is_internal = false)
          OR support_private.has_capability('support.reply')
        )
    )
  );

CREATE POLICY support_attachments_select ON public.support_ticket_attachments
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.support_tickets st
      WHERE st.id = ticket_id
        AND (st.reporter_usuario_id = support_private.current_usuario_id() OR support_private.has_capability('support.view'))
    )
  );

CREATE POLICY support_attachments_insert ON public.support_ticket_attachments
  FOR INSERT TO authenticated
  WITH CHECK (
    uploaded_by_usuario_id = support_private.current_usuario_id()
    AND status = 'pending_upload'
    AND bucket = 'global-connect-support'
    AND checksum_sha256 IS NULL
    AND rejection_reason IS NULL
    AND retention_expires_at IS NULL
    AND EXISTS (
      SELECT 1 FROM public.support_tickets st
      WHERE st.id = ticket_id
        AND (st.reporter_usuario_id = support_private.current_usuario_id() OR support_private.has_capability('support.reply'))
    )
  );

CREATE POLICY support_events_select ON public.support_ticket_events
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.support_tickets st
      WHERE st.id = ticket_id
        AND (st.reporter_usuario_id = support_private.current_usuario_id() OR support_private.has_capability('support.view'))
    )
  );

CREATE OR REPLACE FUNCTION support_private.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO 'public'
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION support_private.prevent_event_mutation()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO 'public'
AS $$
BEGIN
  RAISE EXCEPTION 'support_ticket_events is append-only';
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'set_support_tickets_updated_at') THEN
    CREATE TRIGGER set_support_tickets_updated_at
      BEFORE UPDATE ON public.support_tickets
      FOR EACH ROW EXECUTE FUNCTION support_private.set_updated_at();
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'set_support_ticket_attachments_updated_at') THEN
    CREATE TRIGGER set_support_ticket_attachments_updated_at
      BEFORE UPDATE ON public.support_ticket_attachments
      FOR EACH ROW EXECUTE FUNCTION support_private.set_updated_at();
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'prevent_support_ticket_event_mutation') THEN
    CREATE TRIGGER prevent_support_ticket_event_mutation
      BEFORE UPDATE OR DELETE ON public.support_ticket_events
      FOR EACH ROW EXECUTE FUNCTION support_private.prevent_event_mutation();
  END IF;
END $$;
