name: Deploy Supabase Edge Function

on:
  push:
    branches:
      - main  # Se activa solo cuando subes cambios a la rama 'main'
    paths:
      - 'supabase/functions/handle-new-user/**' # Se activa solo si hay cambios en la función

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link Supabase project
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}

      - name: Deploy Edge Function

        run: supabase functions deploy --no-verify-jwt handle-new-user
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

        run: supabase functions deploy --project-ref $SUPABASE_PROJECT_ID --no-verify-jwt
        

