name: Deploy Supabase Edge Function

on:
  push:
    branches:
      - main
    paths:
      - 'supabase/functions/handle-new-user/**'

jobs:
  deploy-edge-function:
    runs-on: ubuntu-latest
    
    # Asegúrate de que los secretos estén disponibles para los comandos
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy Edge Function
        run: |
          supabase functions deploy handle-new-user --project-ref $SUPABASE_PROJECT_ID --no-verify-jwt