name: Deploy Supabase Edge Function

on:
  push:
    branches:
      - main
    paths:
      - 'supabase/functions/handle-new-user/**'
      - 'supabase/import_map.json' # Añadimos esto para que también se active si solo cambias el import map

jobs:
  deploy-edge-function:
    runs-on: ubuntu-latest
    
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }} # Aunque no se use en deploy, es buena práctica tenerla
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy Edge Function
        run: |
          supabase functions deploy handle-new-user --project-ref $SUPABASE_PROJECT_ID --no-verify-jwt --import-map supabase/import_map.json